on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - main
name: release
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
